add position
protenot/otus-css-Olga_Belaya pull request #3
Opened 2023-01-31 15:41 UTC by protenot

2023-02-02 09:32 UTC, lipa88-mk commented
По макету фонова картинка тянется не бесконечно, это дизайнер показал вот так: 
![image](https://user-images.githubusercontent.com/65017545/216286102-53234d92-55ee-40eb-bb78-47ed725d1571.png)
Этот блок может тянуться, но в какой-то момент он фиксируется на его максимальной ширине по макету, а дальше идут белые края.

2023-02-02 09:44 UTC, lipa88-mk requested changes
Хорошая работа! Можно еще немного добавить моментов из блочной модели, чтобы закрепить работу с позиционированием и отступами вместе.

2023-02-02 09:44 UTC, lipa88-mk commented on index.html
> +   <header class="header-main">
Это не хедер, это просто секция. Хедер уже есть выше) И в нем было бы хорошо кнопочку тоже сделать по центру страинцы)

2023-02-02 09:44 UTC, lipa88-mk commented on style/style.css
> +
вот тут нужно дописать ограничение на растягивание и центрирование

2023-02-02 09:44 UTC, lipa88-mk commented on style/style.css
> +.title-div{
название класса лучше не со словом div, а блок, бокс и так далее, тк семантически див в любой момент может стать чем-то другим

2023-02-02 09:44 UTC, lipa88-mk commented on style/style.css
> +    height: 56%;
высоту тут можно не указывать, (тем более что в % она считается от ширины) а использовать подход с паддингами из лекции по блочной модели для создания "распорки" для контента внутри.

2023-02-02 09:44 UTC, lipa88-mk commented on style/style.css
> +    left:25%;
В целом так можно, но может быть есть какой-то способ как автоматически центрировать блок внутри другого блока? Например, с использованием `transform`?

2023-02-02 09:44 UTC, lipa88-mk commented on style/style.css
> +    padding-bottom: 1.125rem;
Опять же в лекции по блочной модели говорили, почему такая реализация не самая удобная

2023-02-02 09:44 UTC, lipa88-mk commented on style/style.css
> +   padding-bottom: 5.625rem;
Так все таки марджин или паддинг?) И точно ли к этому элементу?)

2023-02-02 09:44 UTC, lipa88-mk commented on style/style.css
> +   padding-bottom: 5.625rem;
А как быть, если заказчик попросит поменять строчки местами?

2023-02-06 15:05 UTC, lipa88-mk requested changes

2023-02-06 15:05 UTC, lipa88-mk commented on style/style.css
> +
Да, хорошее решение, так можно

2023-02-06 15:05 UTC, lipa88-mk commented on style/style.css
> +    /*transform:translate(50% -50%);*/
Если вы хотите сдвинуть элемент по 2 осям, то значения должны разделяться запятой: `transform: translate(x, y)`, либо `transform: translateX(x) translateY(x)` это два варианта одной и той же записи

2023-02-06 15:05 UTC, lipa88-mk commented on style/style.css
> +    left:25%;
Ну и если используем трансформ, то тут лево и верх будут тоже 50%

2023-02-06 16:23 UTC, protenot commented on style/style.css
> +    left:25%;
Спасибо, разобралась, срабатывает если  top 50%, а left 0%

2023-02-06 19:25 UTC, merged