Dz testimonials
protenot/otus-css-Olga_Belaya pull request #5
Opened 2023-02-14 16:14 UTC by protenot

2023-02-19 09:39 UTC, lipa88-mk requested changes
Хорошая работа! Несколько моментов обозначила в комментариях ниже.

2023-02-19 09:39 UTC, lipa88-mk commented on style/style.css
> +    position: absolute;
А нужно ли тут позиционирование? Элемент первый в разметке и первый на макете, зачем его позиционировать за предел секции, если есть обычные марджин и паддинг?

2023-02-19 09:39 UTC, lipa88-mk commented on style/style.css
> +    box-sizing: border-box;
Это лучше добавить в селектор `*`, который, к слову, должен быть самый первый, до `html`)

2023-02-19 09:39 UTC, lipa88-mk commented on style/style.css
> +    grid-template-rows: 1005;
Свойство написано с ошибкой и не работает
![image](https://user-images.githubusercontent.com/65017545/219940176-110b4172-dbd3-4d71-9eb4-4070c6eb650d.png)
Такие вещи нужно проверять валидатором до создания комита, чтобы себя перепроверить. Да и в просмотре кода браузер это подсказывает.

2023-02-19 09:39 UTC, lipa88-mk commented on style/style.css
> +    grid-template-rows: 1005;
И я бы сказала, что тут сетка в 2 столбца, в левом текст еще и повернут. Ничто не запрещает вам добавлять обертки в виде дивов, чтобы сгруппировать элементы :) Это не повлияет на семантику и поможет вам выстроить сетку удобным способом, создав новый грид/флекс контейнер для работы.

2023-02-19 09:39 UTC, lipa88-mk commented on style/style.css
> +.testimonials-block{
Тут не хватает выравнивания картинки и текста по центру 
![image](https://user-images.githubusercontent.com/65017545/219940352-c676562b-daca-47c4-945f-8e40de8eabae.png)

2023-02-20 07:58 UTC, protenot commented on style/style.css
> +    position: absolute;
В данном случае позиционирование позволяет избежать создания лишних дивов, на мой взгляд), но исправила

2023-02-20 07:59 UTC, protenot commented on style/style.css
> +    box-sizing: border-box;
Тут не очень поняла, какие строчки добавить в селектор *. в селектор html уже добавлены базовый размер шрифта и межстрочное расстояние. Остальное частности, которые не могут быть  закреплены за всем документом как мне кажется). селектор * поместила перед html

2023-02-20 07:59 UTC, protenot commented on style/style.css
> +    grid-template-rows: 1005;
Это все-таки вкусовые вещи, оставлю 3, если не возражаете.

2023-02-20 16:21 UTC, lipa88-mk commented on style/style.css
> +    box-sizing: border-box;
`box-sizing: border-box;`

2023-02-21 07:07 UTC, merged