Dz designers
protenot/otus-css-Olga_Belaya pull request #6
Opened 2023-02-16 12:05 UTC by protenot

2023-02-19 10:37 UTC, lipa88-mk requested changes
Хорошая работа, согласна с флексовой сеткой. Верно сделали добавление второго класса `huge` (можно design-item-huge). И еще пара моментов ниже:

2023-02-19 10:37 UTC, lipa88-mk commented on style/style.css
> + .design-list{
Первое, что сразу же видим - вертикальный скролл. 
![image](https://user-images.githubusercontent.com/65017545/219942371-c79201a6-c0af-4d32-9fc1-c64456e7ecf3.png)
В данной ситуации он не нужен, это показывает, что содержимое не поместилось в ячейку. Горизонтальный, при добавлении 2-3 новых дизайнеров, еще можно понять, а вертикаль - не совсем.

2023-02-19 10:37 UTC, lipa88-mk commented on style/style.css
> +
Также, если используете список, то не забывайте скрывать маркеры: 
![image](https://user-images.githubusercontent.com/65017545/219942523-fc8fdea4-3aff-4f8a-ba7a-e2d83501745e.png)

2023-02-19 10:37 UTC, lipa88-mk commented on style/style.css
> +    margin-right: 5.1%;
Вместо того, чтобы помнить, что у последнего всегда должен быть отступ и не потерять этот класс в разметке, можно использовать `:last-child` или вообще вынести отступ в секцию. Либо, если подумать о добавлении новых дизайнеров, это пространство вообще можно представить как просто оставшееся свободное на данный момент, пока не добавлено еще что-то.

2023-02-19 10:37 UTC, lipa88-mk commented on style/style.css
> + .design-item{
Вот тут есть своя микро-сетка: расстояние между картинкой и текстовыми элементами и их оформление пока что не готово: 
![image](https://user-images.githubusercontent.com/65017545/219942738-559b3d28-3b8b-4f56-8525-96d9ee7a676b.png)
Макет: 
![image](https://user-images.githubusercontent.com/65017545/219942762-3321b239-6e9a-4102-9b18-5feb11d0930f.png)

Шрифты и отступы надо скорректировать немного.

2023-02-20 08:34 UTC, protenot commented on style/style.css
> + .design-list{
Мария, у меня прокрутки не возникает, на всякий случай ограничила overflow-x, чтоб ось y не задействовать

2023-02-20 08:34 UTC, protenot commented on style/style.css
> + .design-item{
такое ощущение что мы смотрим разные версии,  у меня практически совпадает текст с макетом, у Вас мой текст наезжает друг на друга отправлю еще раз, поменяла только межбуквенное расстояние

2023-02-27 14:14 UTC, lipa88-mk commented on style/style.css
> + .design-list{
Думается, что оверфлоу тут в целом не нужен, либо задать на каждую ось своё. так же важно помнить, что скроллы занимают некоторое место, сужая контент

2023-02-27 16:37 UTC, merged